export { Cinemascope } from '@scripting/properties/Cinemascope.js'
export { Collision } from '@scripting/properties/Collision.js'
export { ControlZone } from '@scripting/properties/ControlZone.js'
export { Interactivity } from '@scripting/properties/Interactivity.js'
export { Invulnerability } from '@scripting/properties/Invulnerability.js'
export { Label } from '@scripting/properties/Label.js'
export { Material } from '@scripting/properties/Material.js'
export { PlayerControls } from '@scripting/properties/PlayerControls.js'
export { PlayerInterface } from '@scripting/properties/PlayerInterface.js'
export { Scale } from '@scripting/properties/Scale.js'
export { Shadow } from '@scripting/properties/Shadow.js'
export { Speed } from '@scripting/properties/Speed.js'
export { StackSize } from '@scripting/properties/StackSize.js'
export { Transparency } from '@scripting/properties/Transparency.js'
export { Variable } from '@scripting/properties/Variable.js'

export type { MaterialType } from '@scripting/properties/Material.js'
export type { VariableType } from '@scripting/properties/Variable.js'
