export { getVertices, getNonIndexedVertices } from '@tools/mesh/getVertices.js'
export { loadOBJ } from '@tools/mesh/loadOBJ.js'
export { makeBumpy } from '@tools/mesh/makeBumpy.js'
export { scaleUV, flipUVHorizontally, flipUVVertically, normalizeUV } from '@tools/mesh/scaleUV.js'
export { toArxCoordinateSystem } from '@tools/mesh/toArxCoordinateSystem.js'
export { transformEdge } from '@tools/mesh/transformEdge.js'
export { translateUV } from '@tools/mesh/translateUV.js'
export { connectEdgeTo } from '@tools/mesh/connectEdgeTo.js'
export { categorizeVertices } from '@tools/mesh/categorizeVertices.js'
export { addPoint } from '@tools/mesh/addPoint.js'
export { getLowestPolygonIdx } from '@tools/mesh/getLowestPolygonIdx.js'

export type { GeometryVertex } from '@tools/mesh/getVertices.js'
